version: '3.8'

services:
  backend:
    build:
      dockerfile: dockerfile_python
    ports:
      - 23402:8000
    env_file:
      - ./envs.env

  frontend:
    build:
      dockerfile: dockerfile_frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
